## Data Cleaning and Preparation
Before a machine learning model can find patterns in data, that data must be mathematically sound. Most ML algorithms (like those in Scikit-Learn) will throw a fatal error the moment they encounter a missing value.

In Pandas, missing data usually shows up as `NaN` (Not a Number) or `None`.

Filtering out (or dropping) missing data is the simplest way to handle this, but it must be done strategically. If you just delete everything that has a blank cell, you might throw away 80% of your valuable dataset.

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display
# This forces the beautiful HTML formatting for both outputs!

In [65]:
# Read the csv file
# usecols did what , Grabs only columns 0 through 7, ignoring anything after the
# 8th comma completely.
df = pd.read_csv('messy_registry_data.csv', index_col=False, usecols=range(8), skipinitialspace=True)
df

,Carrier_ID,Company Name,Registration_Date,Fleet_Size,Contact_Number,HQ_Location,Insurance_Status,Notes
0,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,NaN
1,MC-1002,Global Freight Co,2023/04/18,42,+1-555-987-6543,chicago IL,active,Safety audit pending
2,mc-1003,Swift Transport,01-15-24,Five,555.555.0199,Los Angeles; CA,Pending,NaN
3,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,Duplicate entry
4,NaN,Desert Haulers Inc.,11/11/2022,8,NaN,Phoenix AZ,EXPIRED,NaN
5,MC-1005,Northern Routes LTD,09-30-2023,100+,555-111-2222,Seattle WA,Active,NaN
6,MC-1006,East Coast Transit,NaN,twelve,(555) 333-4444,"Miami, FL",NaN,Missing reg date
7,MC-1007,horizon express,24-01-2024,3,+1 555 777 8888,"Denver, CO",aCTIVE,NaN
8,MC-1008,Titan Movers,03/05/2021,NaN,5558889999,Dallas TX,Canceled,Check DOT number
9,MC-1009,NaN,10-10-2023,1,NaN,"Austin, TX",Active,Owner operator

In [66]:
"""
Step 1: The diagnosis (Finding the Missing Data)

A good analyst never deletes data blindly. First, we must quantify the damage.
Assuming we have loaded messy_registry_data.csv into a variable named df.
"""

df.info()
# This returns the count fo missing values in every single column
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Carrier_ID         9 non-null      str
 1   Company Name       9 non-null      str
 2   Registration_Date  9 non-null      str
 3   Fleet_Size         9 non-null      str
 4   Contact_Number     8 non-null      str
 5   HQ_Location        10 non-null     str
 6   Insurance_Status   9 non-null      str
 7   Notes              5 non-null      str
dtypes: str(8)
memory usage: 772.0 bytes

Carrier_ID           1
Company Name         1
Registration_Date    1
Fleet_Size           1
Contact_Number       2
HQ_Location          0
Insurance_Status     1
Notes                5
dtype: int64

In [67]:
"""
Step 2: The Nuclear Option (Dropping any row with a missing value)

The most basic method is to drop a row entirely if it is missing even one piece
of information. We use dropna() method for this.
"""
# clean_df= df.dropna()
# print(clean_df.head())

'\nStep 2: The Nuclear Option (Dropping any row with a missing value)\n\nThe most basic method is to drop a row entirely if it is missing even one piece\nof information. We use dropna() method for this.\n'

In [68]:
"""
Step 3: The Safe Cleanup (Dropping completely empty rows)

Sometimes, web scrapers or Excel exports create completely blank rows at the
bottom of a file. 

So we'll drop a row only if every single columns is NaN.
"""

# Drops a row ONLY if all of its values are missing.
# df_clean = df.dropna(how='all')

# print(df_clean.head())

"\nStep 3: The Safe Cleanup (Dropping completely empty rows)\n\nSometimes, web scrapers or Excel exports create completely blank rows at the\nbottom of a file. \n\nSo we'll drop a row only if every single columns is NaN.\n"

In [69]:
"""
Step 4: The Surgeon's Scalpel (Trageted Dropping)

This is the industry standard. Instead of looking at the whole row, we drop rows
based on missing values in critical columns.

Look at ook at our dataset. If a row is missing a "Notes" section, we don't care.
We can still use that data. But if a row is missing its Carrier_ID, that data 
is completely useless to us—we can't identify the company!
"""

# Drops rows Only if the Carrier_ID is missing.
# df_clean = df.dropna(subset=['Carrier_ID'])
# print(df_clean.head())

'\nStep 4: The Surgeon\'s Scalpel (Trageted Dropping)\n\nThis is the industry standard. Instead of looking at the whole row, we drop rows\nbased on missing values in critical columns.\n\nLook at ook at our dataset. If a row is missing a "Notes" section, we don\'t care.\nWe can still use that data. But if a row is missing its Carrier_ID, that data \nis completely useless to us—we can\'t identify the company!\n'

#### Filling in Missing values

In Pandas, the workhorese for this is the .fillna() method. The strategy you choose depends entirely on the type of data in that column.

**1. The Constant Fill ( Best for Text/categorical Data)**

if  a non-crirtical text column is missing, we simply replace the NaN with a standardized placeholder. This prevents our ML models from crashing while explicitly marking the data as missing.

In [70]:
df

,Carrier_ID,Company Name,Registration_Date,Fleet_Size,Contact_Number,HQ_Location,Insurance_Status,Notes
0,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,NaN
1,MC-1002,Global Freight Co,2023/04/18,42,+1-555-987-6543,chicago IL,active,Safety audit pending
2,mc-1003,Swift Transport,01-15-24,Five,555.555.0199,Los Angeles; CA,Pending,NaN
3,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,Duplicate entry
4,NaN,Desert Haulers Inc.,11/11/2022,8,NaN,Phoenix AZ,EXPIRED,NaN
5,MC-1005,Northern Routes LTD,09-30-2023,100+,555-111-2222,Seattle WA,Active,NaN
6,MC-1006,East Coast Transit,NaN,twelve,(555) 333-4444,"Miami, FL",NaN,Missing reg date
7,MC-1007,horizon express,24-01-2024,3,+1 555 777 8888,"Denver, CO",aCTIVE,NaN
8,MC-1008,Titan Movers,03/05/2021,NaN,5558889999,Dallas TX,Canceled,Check DOT number
9,MC-1009,NaN,10-10-2023,1,NaN,"Austin, TX",Active,Owner operator

In [71]:
# let's delete the Carrier_ID , which is NaN , since there's no use of it.
cleaned_df = df.dropna(subset=['Carrier_ID'])
cleaned_df

,Carrier_ID,Company Name,Registration_Date,Fleet_Size,Contact_Number,HQ_Location,Insurance_Status,Notes
0,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,NaN
1,MC-1002,Global Freight Co,2023/04/18,42,+1-555-987-6543,chicago IL,active,Safety audit pending
2,mc-1003,Swift Transport,01-15-24,Five,555.555.0199,Los Angeles; CA,Pending,NaN
3,MC-1001,Apex Logistics LLC,12-05-2023,15 trucks,(555) 123-4567,"New York, NY",Active,Duplicate entry
5,MC-1005,Northern Routes LTD,09-30-2023,100+,555-111-2222,Seattle WA,Active,NaN
6,MC-1006,East Coast Transit,NaN,twelve,(555) 333-4444,"Miami, FL",NaN,Missing reg date
7,MC-1007,horizon express,24-01-2024,3,+1 555 777 8888,"Denver, CO",aCTIVE,NaN
8,MC-1008,Titan Movers,03/05/2021,NaN,5558889999,Dallas TX,Canceled,Check DOT number
9,MC-1009,NaN,10-10-2023,1,NaN,"Austin, TX",Active,Owner operator

#### Removing the Duplicates

In the world of data, duplicates are dangerous. If you are training a machine learning model to predict shipping costs, feeding it the exact same company twice gives that company unfair weight in the algorithm's "memory."

**Step 1: The Diagonals (`duplicated()`)**
Before we delete anything, we should see what Pandas considers a duplicate. By default, Pandas only flags a row as a duplicate if **every single columns** matches exactly.

In [72]:
# Returns True for any row that is an exact copy of a previous row
cleaned_df.duplicated().sum()

np.int64(0)

**Step 2: Targeted Duplication (The `subset` Parameter)**

Just like we did with missing data, we have to tell Pandas to focus only on the critical columns. If two rows share the exact same `Carrier_ID`, it is the same company, regardless of what the `Notes` column says

In [73]:
# Check for duplicates based ONLY ON Carrier_ID
print(cleaned_df.duplicated(subset=['Carrier_ID']).sum())

1

**Step 3: The Execution (`drop_duplicates()`)**

To actually remove the rows, we use `.drop_duplicates()`. But when you have two versions of the same row, you have to decide which one survives. We control this using the keep parameter.

we have three strategic choices:
- `keep='first'` **(The default):** Keeps the very first instance it sees reading top-to-bottom and deletes all subsequent copies.
- `keep='last` : Deletes the first instances and keeps the very last copy at the bottom of the file (useful if you know newer data is appended to the bottom).
- `keep=False` **(The Nuclear Options)**: If it finds a duplicate, it deletes all versions of it. Neither survives. (Useful in fraud detection where any duplication is highly suspicious).

In [74]:
# Drop duplicates based on the ID, keeping the first occurence, and overwriting the variable
cleaned_df = cleaned_df.drop_duplicates(subset=['Carrier_ID'], keep='first')
print(cleaned_df)

  Carrier_ID         Company Name Registration_Date Fleet_Size  \
0    MC-1001   Apex Logistics LLC        12-05-2023  15 trucks
1    MC-1002   Global Freight Co         2023/04/18         42
2    mc-1003      Swift Transport          01-15-24       Five
5    MC-1005  Northern Routes LTD        09-30-2023       100+
6    MC-1006   East Coast Transit               NaN     twelve
7    MC-1007      horizon express        24-01-2024          3
8    MC-1008         Titan Movers        03/05/2021        NaN
9    MC-1009                  NaN        10-10-2023          1

    Contact_Number      HQ_Location Insurance_Status                 Notes
0   (555) 123-4567     New York, NY           Active                   NaN
1  +1-555-987-6543       chicago IL           active  Safety audit pending
2     555.555.0199  Los Angeles; CA          Pending                   NaN
5     555-111-2222       Seattle WA           Active                   NaN
6   (555) 333-4444        Miami, FL              NaN      Missing reg date
7  +1 555 777 8888       Denver, CO           aCTIVE                   NaN
8       5558889999        Dallas TX         Canceled      Check DOT number
9              NaN       Austin, TX           Active        Owner operator

#### The Date Time Fixing

**The Fix: `pd.to_datetime()`**
Pandas has a highly intelligent built-in parser that  can look at a messy column of mixed date formats and standardize almost all of them instantly into a uniform `YYYY-MM-DD` format.

In [75]:
%%capture
# Convert the messy text into standard Pandas Datetime objects
cleaned_df['Registration_Date'] = pd.to_datetime(cleaned_df['Registration_Date'], errors='coerce', format='mixed')
cleaned_df

In [76]:
# import pandas as pd
# import numpy as np

# # 1. Reload the raw data from scratch.
# df = pd.read_csv('messy_registry_data.csv', index_col=False, skipinitialspace=True)

# # 2. Fix the invisible whitespace
# df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

# # 3. Drop the missing IDs (use .copy() to prevent Pandas Warnings later)
# cleaned_df = cleaned_df.dropna(subset=['Carrier_ID']).copy()
# # print(cleaned_df)

# # 4. Drop the duplicates 
# cleaned_df = cleaned_df.drop_duplicates(subset=['Carrier_ID'], keep='first')
# # cleaned_df

# # 5. The Date Fix (Now it should work)
# cleaned_df['Registration_Date'] = pd.to_datetime(cleaned_df['Registration_Date'], format='mixed')
# cleaned_df

In [77]:
import pandas as pd
import numpy as np

# 1. Load the data into a BRAND NEW variable name (test_df)
test_df = pd.read_csv('messy_registry_data.csv', index_col=False, skipinitialspace=True, usecols=range(8))

# 2. Let's look at the raw data BEFORE we touch it
print("--- 1. RAW TEXT DATES ---")
print(test_df['Registration_Date'].dropna().head())

# 3. Now apply the conversion
test_df['Registration_Date'] = pd.to_datetime(test_df['Registration_Date'], format='mixed', errors='coerce')

# 4. Let's look at the data AFTER the conversion
print("\n--- 2. AFTER CONVERSION ---")
print(test_df[['Carrier_ID', 'Registration_Date']].head())

--- 1. RAW TEXT DATES ---
0    12-05-2023
1    2023/04/18
2      01-15-24
3    12-05-2023
4    11/11/2022
Name: Registration_Date, dtype: str

--- 2. AFTER CONVERSION ---
  Carrier_ID Registration_Date
0    MC-1001        2023-12-05
1    MC-1002        2023-04-18
2    mc-1003        2024-01-15
3    MC-1001        2023-12-05
4        NaN        2022-11-11

In [78]:
# Remove the NaN vlaue on Carrier_ID
cleaned_test_df = test_df.dropna(subset=['Carrier_ID']).copy()
# cleaned_test_df

# Remove the duplicates
cleaned_test_df = cleaned_test_df.drop_duplicates(subset=['Carrier_ID'], keep='first')
cleaned_test_df

,Carrier_ID,Company Name,Registration_Date,Fleet_Size,Contact_Number,HQ_Location,Insurance_Status,Notes
0,MC-1001,Apex Logistics LLC,2023-12-05,15 trucks,(555) 123-4567,"New York, NY",Active,NaN
1,MC-1002,Global Freight Co,2023-04-18,42,+1-555-987-6543,chicago IL,active,Safety audit pending
2,mc-1003,Swift Transport,2024-01-15,Five,555.555.0199,Los Angeles; CA,Pending,NaN
5,MC-1005,Northern Routes LTD,2023-09-30,100+,555-111-2222,Seattle WA,Active,NaN
6,MC-1006,East Coast Transit,NaT,twelve,(555) 333-4444,"Miami, FL",NaN,Missing reg date
7,MC-1007,horizon express,2024-01-24,3,+1 555 777 8888,"Denver, CO",aCTIVE,NaN
8,MC-1008,Titan Movers,2021-03-05,NaN,5558889999,Dallas TX,Canceled,Check DOT number
9,MC-1009,NaN,2023-10-10,1,NaN,"Austin, TX",Active,Owner operator

In [79]:
import re

def clean_fleet(value):
    if pd.isna(value):
        return pd.NA
    val_str = str(value).lower().strip()
    # Dictionary to map common text numbers to digits
    word_to_num = {
        'one' : '1', 'two': '2', 'three': '3', 'four': '4', 'five': '5',
        'six': '6', 'seven': '7', 'eight': '8', 'nine': '9', 'ten': '10',
        'eleven': '11', 'twelve': '12'
    }
    
    # If the exact string matches a key in our dictionary, replace it with
    # the digit version
    if val_str in word_to_num:
        val_str = word_to_num[val_str]
    
    # The Regex Magic: Replace any non-digit character (\D) with nothing
    digits_only = re.sub(r'\D', '', val_str)

    # If stripping letters left us with an empty string, return missing
    if digits_only == '':
        return pd.NA
    
    # Convert the final clean string into an integer
    return int(digits_only)

# 2. Apply the function to the column
cleaned_test_df['Fleet_Size'] = cleaned_test_df['Fleet_Size'].apply(clean_fleet)

# 3. Convert the 'Fleet_Size' into Int64.
cleaned_test_df['Fleet_Size'] = cleaned_test_df['Fleet_Size'].astype('Int64')

cleaned_test_df

,Carrier_ID,Company Name,Registration_Date,Fleet_Size,Contact_Number,HQ_Location,Insurance_Status,Notes
0,MC-1001,Apex Logistics LLC,2023-12-05,15,(555) 123-4567,"New York, NY",Active,NaN
1,MC-1002,Global Freight Co,2023-04-18,42,+1-555-987-6543,chicago IL,active,Safety audit pending
2,mc-1003,Swift Transport,2024-01-15,5,555.555.0199,Los Angeles; CA,Pending,NaN
5,MC-1005,Northern Routes LTD,2023-09-30,100,555-111-2222,Seattle WA,Active,NaN
6,MC-1006,East Coast Transit,NaT,12,(555) 333-4444,"Miami, FL",NaN,Missing reg date
7,MC-1007,horizon express,2024-01-24,3,+1 555 777 8888,"Denver, CO",aCTIVE,NaN
8,MC-1008,Titan Movers,2021-03-05,<NA>,5558889999,Dallas TX,Canceled,Check DOT number
9,MC-1009,NaN,2023-10-10,1,NaN,"Austin, TX",Active,Owner operator